### ISSUE TITLE
[Bug] Inaccurate maximum bitrate URL

### ISSUE THREAD

**Issue by TheIllusiveC4** [koenvanzuijlen/giantbomb-show-dl#16]
Version: 1.8.0

The current workaround for the 8000 kbps URL not being returned by the API is:
https://github.com/koenvanzuijlen/giantbomb-show-dl/blob/2f36fb979905cbc260808b75b16d1684797780b4/src/bin.ts#L319

This method will not work for videos on 2022-03-16 and afterwards since they began to use a different template entirely (i.e. "vf_ql_tunic_031622_027_1_1080h5000k.mp4" from "Quick Look: Tunic" with GUID 2300-17633).

To accurately grab the maximum bitrate 8000 kbps URLs for these videos, updates would need to be made to the code to include mapping from "5000k" -> "8000k".

**Comment by koenvanzuijlen** [comment]
Thanks for reporting this, it has been fixed in version 1.9.0
