### ISSUE TITLE
Store last completed page when archiving

### ISSUE THREAD

**Issue by XAMPPRocky** [koenvanzuijlen/giantbomb-show-dl#26]
Hello 👋 I've been using this great tool to archive videos (thank you so much for working on it), but now that I'm getting to 2014, I've noticed that the tool spends a lot of time going through old pages before it gets back to where it left off, and now I repeatedly see a timeout on getting the pages so I'm unable to archive past page 79/80. It would be great if it could mark a page as completed once all videos have been successfully downloaded, so that it can start from the last incomplete page, rather than always needing to start from 2008.

```
Retrieving videos page 79
	Error: Failed to videos page: timeout of 5000ms exceeded
💣 giantbomb-show-dl is done for 7900 video(s)! 💣
3 downloads failed! Re-run the command to retry.
```

**Comment by koenvanzuijlen** [comment]
Hi,

I was running into this issue myself too, but what I did was is actually pass along the `from_date` argument you can give to the Giant Bomb API. So let's say if you would add `--from_date 2014-01-01` it would only go through the videos that were published from 2014 onward.

This should be in the last version (2.1.0)

Hopefully that helps! Let me know if it does not.

**Comment by XAMPPRocky** [comment]
Thank you for the advice. I'll try that, I will say that I think the app storing what pages are have successfully completed would be a better solution. Because I leave this program running over night and sometimes there's a random network failure and the program moves on (which is good), but with the `from_date` solution I would have to manually go through the logs to make sure I didn't miss anything before I could move up the `from_date`, where as if the program stored the last successful completed page, it could figure out that for me.

**Comment by koenvanzuijlen** [comment]
That is a good point, I will look into saving the last fully successful page specifically for the archiving function. I'll reopen this to keep track of that.

**Comment by koenvanzuijlen** [comment]
This has been added to version 2.2.0.

You will need to go through all the pages once again, and after that it should work.

**Comment by XAMPPRocky** [comment]
Thank you for working on this and this amazing project! 🙏
