### ISSUE TITLE
Add retrying to download failures

### ISSUE THREAD

**Issue by XAMPPRocky** [koenvanzuijlen/giantbomb-show-dl#31]
Hello again 🙂 Currently `giantbomb-show-dl` when a download fail will immediately proceed to the next video. It would be nice if depending on the error (when it is a network error and not something like #30) that the tool tried to download the same video again.

Additionally I don't know if the giant bomb CDN supports multi-part downloads, but as part of retrying it would be great if it could reuse the part its already downloaded, making it quicker to download and reducing overall network traffic.

**Comment by koenvanzuijlen** [comment]
This would indeed be a nice feature, but probably not something I have time to look at soon. I will keep for when I have time in the future

**Comment by koenvanzuijlen** [comment]
Resuming of interrupted downloads (in the next run) is now implemented, retrying will be a future update.

**Comment by XAMPPRocky** [comment]
Thank you again for improving this tool 🙂

**Comment by koenvanzuijlen** [comment]
@XAMPPRocky Version 2.4.0 now includes retries, by default it will retry 2 times after a failure. Can be configured with `--retries` options

**Comment by XAMPPRocky** [comment]
Great thank you again for adding these improvements, can't wait to continue archiving with them 🙏
